# Generated by Django 5.2.6 on 2025-09-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-created_at'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(choices=[('Fiction', 'Fiction'), ('Non-fiction', 'Non-fiction'), ('Science', 'Science'), ('History', 'History')], default='Fiction', max_length=50),
        ),
        migrations.AddField(
            model_name='books',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(help_text='Write a short description'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Book Title'),
        ),
    ]
